In [5]:
import numpy as np

In [71]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
M1 = np.array([2,5,3,4,0,8,1,3,0]).reshape(3,3)
V1 = np.array([[-3,0,2]]).reshape(3,1)

[[2 5 3]
 [4 0 8]
 [1 3 0]] 

 [[-3]
 [ 0]
 [ 2]]


In [92]:
np.dot(np.linalg.inv(M1),V1)

array([[ 5.42857143],
       [-1.14285714],
       [-2.71428571]])

In [86]:
np.linalg.solve(M1,V1)

array([[ 5.42857143],
       [-1.14285714],
       [-2.71428571]])

In [69]:
M1_D = np.linalg.det(M1)
M1_ds = []
for i in range(3):
    md = M1.copy()
    md[:,i] = V1.T
    M1_ds.append(np.linalg.det(md)/M1_D)
M1_ds

[5.428571428571429, -1.142857142857143, -2.7142857142857144]